package csc366.jpademo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

// This class will be automatically implemented by Spring and made available as a "Bean" named personRepository
@Repository
public interface OwnerRepository extends JpaRepository<Owner, Long> {

    // query inferred from method name, code generated by Spring Framework
    Owner findByOwnerId(int ownerId);
/*
    // Native SQL query (validity not checked, invalid SQL will cause runtime
    // exception)
    @Query(value = "select * from Owner as o where o.first_name = :name or o.last_name = :name", nativeQuery = true)
    Customer findByNameSql(@Param("name") String name);

    @Modifying
    @Query("update Owner o set o.firstName = :newName where o.firstName = :oldName")
    void updateFirstName(@Param("oldName") String oldName, @Param("newName") String newName);

    @Modifying
    @Query("update Owner o set o.lastName = :newName where o.lastName = :oldName")
    void updateLastName(@Param("oldName") String oldName, @Param("newName") String newName);

*/
}
